/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: operations["AppController_getHello"];
  };
  "/todo": {
    /** Todo Todo一覧を返す */
    get: operations["TodoController_findAll"];
    /** Todo を登録する */
    post: operations["TodoController_create"];
  };
  "/todo/{id}": {
    /** Todo 単体取得API */
    get: operations["TodoController_findOne"];
    /** Todo を削除する */
    delete: operations["TodoController_remove"];
    /** Todo を更新する */
    patch: operations["TodoController_update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CreateTodoDto: {
      text: string;
      description: string;
      done: boolean;
    };
    TodoDto: {
      id: number;
      text: string;
      /**
       * @description the todo description
       * @example task description
       */
      description: string;
      /**
       * @description the todo status
       * @example false
       */
      done: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    UpdateTodoDto: {
      text: string;
      description: string;
      done: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  AppController_getHello: {
    responses: {
      200: never;
    };
  };
  /** Todo Todo一覧を返す */
  TodoController_findAll: {
    responses: {
      /** @description Todo を一覧で取得する */
      200: {
        content: {
          "application/json": components["schemas"]["TodoDto"][];
        };
      };
    };
  };
  /** Todo を登録する */
  TodoController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateTodoDto"];
      };
    };
    responses: {
      /** @description 登録したメンバー設定を返却 */
      201: {
        content: {
          "application/json; charset=utf-8": components["schemas"]["TodoDto"];
        };
      };
    };
  };
  /** Todo 単体取得API */
  TodoController_findOne: {
    parameters: {
      path: {
        /** @example 1 */
        id: number;
      };
    };
    responses: {
      /** @description The found record */
      200: {
        content: {
          "application/json; charset=utf-8": components["schemas"]["TodoDto"];
        };
      };
    };
  };
  /** Todo を削除する */
  TodoController_remove: {
    parameters: {
      path: {
        /** @example 1 */
        id: number;
      };
    };
    responses: {
      /** @description 削除したTodoを返却 */
      201: {
        content: {
          "application/json; charset=utf-8": components["schemas"]["TodoDto"];
        };
      };
    };
  };
  /** Todo を更新する */
  TodoController_update: {
    parameters: {
      path: {
        /** @example 1 */
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateTodoDto"];
      };
    };
    responses: {
      /** @description 登録したTodoを返却 */
      201: {
        content: {
          "application/json; charset=utf-8": components["schemas"]["TodoDto"];
        };
      };
    };
  };
}
